[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "Console_BSM"
version = "0.1.0"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]

[tool.hatch.build.targets.wheel]
packages = ["app"]
